name: Build and Upload Wheel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools
        run: pip install hatchling

      - name: Build wheel
        run: hatchling build -t wheel

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: api_contract_validator-wheel
          path: dist/*.whl
